# Generated by Django 3.0.4 on 2020-04-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='n/a', max_length=100)),
                ('first_name', models.CharField(default='n/a', max_length=100)),
                ('father_name', models.CharField(default='n/a', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='n/a', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem_text', models.TextField(unique=True)),
                ('poem_title', models.CharField(max_length=200)),
                ('poem_year', models.CharField(blank=True, default=' ', max_length=10, null=True)),
                ('first_line', models.CharField(blank=True, max_length=200, null=True)),
                ('poem_tag', models.ManyToManyField(to='poems.Tag')),
                ('poet_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poems.Poet')),
            ],
        ),
    ]
