# Generated by Django 3.0.4 on 2020-04-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='n/a', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem_text', models.TextField()),
                ('poem_title', models.CharField(max_length=1000)),
                ('first_line', models.CharField(blank=True, max_length=1000, null=True)),
                ('tag', models.ManyToManyField(to='poems.Tag')),
            ],
        ),
    ]
