# Generated by Django 3.0.4 on 2020-04-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='poem_text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='poem_title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
