# Generated by Django 3.0.4 on 2020-04-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_auto_20200419_1559'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='poem',
            managers=[
            ],
        ),
    ]
