# Generated by Django 3.0.5 on 2020-05-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_auto_20200419_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='poet_img',
            field=models.ImageField(blank=True, null=True, upload_to='poems'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='poem_text',
            field=models.TextField(),
        ),
    ]
