# Generated by Django 3.0.5 on 2020-05-18 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_auto_20200517_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poems_amount', models.IntegerField()),
                ('all_words_amount', models.IntegerField()),
                ('unique_words_amount', models.IntegerField()),
                ('top_100_words', models.TextField(verbose_name='Топ-100 слов')),
                ('top_100_nouns', models.TextField(verbose_name='Топ-100 существительных')),
                ('top_100_verbs', models.TextField(verbose_name='Топ-100 глаголов')),
                ('top_100_adjf', models.TextField(verbose_name='Топ-100 прилагательных')),
            ],
        ),
        migrations.AddField(
            model_name='poet',
            name='poet_dictionary',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='poems.AnalyticsInfo'),
        ),
    ]
