# Generated by Django 3.0.5 on 2020-05-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_auto_20200518_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='poet_dictionary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poems.AnalyticsInfo'),
        ),
    ]
