# Generated by Django 3.0.5 on 2020-05-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0006_auto_20200518_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='analyticsinfo',
            name='poet_dictionary_id',
            field=models.IntegerField(default=1, max_length=10, primary_key=True, serialize=False),
        ),
    ]
