# Generated by Django 3.0.5 on 2020-05-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0009_auto_20200518_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
