# Generated by Django 3.0.5 on 2020-05-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0010_auto_20200520_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
