# Generated by Django 3.0.5 on 2020-05-20 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0011_auto_20200520_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.IntegerField()),
                ('poem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poems.Poem')),
            ],
        ),
    ]
