# Generated by Django 3.0.5 on 2020-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0013_auto_20200520_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='custom_id',
            field=models.IntegerField(null=True),
        ),
    ]
