# Generated by Django 3.0.5 on 2020-05-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0015_poem_poem_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='poem_img',
            field=models.ImageField(blank=True, null=True, upload_to='poems'),
        ),
    ]
