# Generated by Django 3.0.5 on 2020-05-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0016_poem_poem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='poem_tag',
            field=models.ManyToManyField(blank=True, to='poems.Tag'),
        ),
    ]
