# Generated by Django 3.0.5 on 2020-05-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0018_auto_20200522_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='custom_id',
            field=models.IntegerField(default=0),
        ),
    ]
