# Generated by Django 3.0.5 on 2020-05-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0019_poem_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='custom_id',
        ),
    ]
