# Generated by Django 3.0.6 on 2020-06-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0022_firstline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ['-id']},
        ),
    ]
