# Generated by Django 3.0.6 on 2020-06-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0023_auto_20200606_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='poem_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='poet_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poems.Poet'),
        ),
    ]
