# Generated by Django 3.0.6 on 2020-06-07 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0025_auto_20200607_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstline',
            name='id',
        ),
        migrations.AlterField(
            model_name='firstline',
            name='poem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='poems.Poem'),
        ),
    ]
