# Generated by Django 3.0.6 on 2020-06-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0026_auto_20200607_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPoem',
            fields=[
                ('poem_audio', models.FileField(blank=True, null=True, upload_to='poems/audio')),
                ('poem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='poems.Poem')),
            ],
        ),
        migrations.DeleteModel(
            name='FirstLine',
        ),
    ]
