# Generated by Django 3.0.6 on 2020-06-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0027_auto_20200615_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioPoem',
        ),
    ]
