# Generated by Django 3.0.4 on 2020-04-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_noun', models.BooleanField(default=False, verbose_name='IS_NOUN')),
                ('is_adjf', models.BooleanField(default=False, verbose_name='IS_ADJF')),
            ],
        ),
    ]
