# Generated by Django 3.0.4 on 2020-04-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryform',
            name='is_verb',
            field=models.BooleanField(default=False, verbose_name='Глаголы'),
        ),
        migrations.AlterField(
            model_name='dictionaryform',
            name='is_adjf',
            field=models.BooleanField(default=False, verbose_name='Прилагательные'),
        ),
        migrations.AlterField(
            model_name='dictionaryform',
            name='is_noun',
            field=models.BooleanField(default=False, verbose_name='Существительные'),
        ),
    ]
