# Generated by Django 3.0.4 on 2020-05-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_poetsform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoetsForm',
        ),
    ]
